import './sass/main.scss';
import './js/utils/references/refs';
import './js/utils/index';
import './templates/notes.hbs';
import './js/utils/app';
import './js/utils/constants/constants';
import './js/utils/Model/NotepadModel';
import './js/utils/handlers/SaveNote';
import './js/utils/handlers/SearchNote';
import './js/utils/handlers/DeleteNote';
import './js/utils/rendering/view'
